version: "3.9"
services:
  database:
    image: "postgres:9.6"
    environment:
      POSTGRES_PASSWORD: b0op1234
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./schema.sql
        target: /docker-entrypoint-initdb.d/schema.sql

  dbadmin:
    image: "dpage/pgadmin4:5.0"
    ports: 
      - 8088:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "SuperSecret"
    
    depends_on:
      - database
  
  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - 8080:8080
    environment: 
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:b0op1234@database:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    
    depends_on:
      - database

  backend:
    build: ./src/backend
    ports:
      - 8081:8081
    depends_on:
      - hasura

  order-app-frontend:
    build: ./src/order-app-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
